# Generated by Django 3.1.4 on 2021-01-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('event_text', models.CharField(max_length=300)),
                ('event_image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
